config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  resources :pages
  resources :fields do
    resources :bookings, only: [:new, :create]
  end
    resources :bookings, only: [:show]
    resources :users, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :field
end

app/models/field.rb
class Field < ApplicationRecord
  belongs_to :user
  has_one_attached :photo
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  reverse_geocoded_by :latitude, :longitude
  after_validation :reverse_geocode

  include PgSearch::Model
  pg_search_scope :search_by_name_and_address,
    against: [ :name, :address ],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :fields, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit::Authorization
  before_action :configure_permitted_parameters, if: :devise_controller?
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :phone_number, :address, :birthday])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :phone_number, :address, :birthday])
  end
  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin_user)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_field, only: %i[new create show]

  def show
    @field = Field.find(params[:field_id])
    @booking = Booking.find(params[:id])
  end

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.field = @field
    @booking.save!
    redirect_to field_booking_path(@field, @booking.id)
  end

  private

  def set_field
    @field = Field.find(params[:field_id])
  end

  def booking_params
    params.require(:booking).permit(:start_time, :end_time)
  end
end

app/controllers/fields_controller.rb
class FieldsController < ApplicationController
  def index
    if params[:query].present?
      @fields_search = Field.search_by_name_and_address(params[:query])
      @fields = policy_scope(@fields_search)
    else
      @fields = policy_scope(Field)
    end

    @markers = @fields.geocoded.map do |field|
      { lat: field.latitude, lng: field.longitude, info_window_html: render_to_string(partial: "info_window", locals: {field: field})}
    end
  end

  def show
    @field = Field.find(params[:id])
    @booking = Booking.new
    authorize @field
  end

  def new
    @field = Field.new
    authorize @field
  end

  def create
    @field = Field.new(field_params)
    @field.user = current_user
    authorize @field
    if @field.save!
      redirect_to fields_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @field = Field.find(params[:id])
    authorize @field
  end

  def update
    @field = Field.find(params[:id])
    authorize @field
    @field.update(params[:field])
  end

  def destroy
    @field = Field.find(params[:id])
    authorize @field
    @field.destroy
    redirect_to fields_path(@field), status: :see_other
  end

  private

  def field_params
    params.require(:field).permit(:price, :name, :address, :number_of_players, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
    authorize @user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/show.html.erb
<h1>Teste</h1>

app/views/fields/_info_window.html.erb
<h2><%= field.name %></h2>
<p><%= field.address %></p>

app/views/fields/index.html.erb
<body style = "background-color: #667F63">

<div style="text-align: -webkit-center;" class="mt-3 p-3 text-white">
<h5>ENCONTRE AQUI</h5>
 <h1>UM CAMPO PARA JOGAR</h1>
 <div class = "w-50 m-5"><%= form_with url: fields_path, method: :get, class: "d-flex" do %>
    <%= text_field_tag :query,
      params[:query],
      class: "form-control",
     placeholder: "Find a field"
   %>
    <%= submit_tag "Search", class: "btn btn-primary" %>
  <% end %></div>
</div>

      <div class="container pb-5 mb-5">
        <div class="row">
            <% @fields.each do |field| %>
            <div class="col-4 mt-3">
                <div class="card" style="width: 18rem;">
                  <%= cl_image_tag field.photo.key, height: 250, width: 250, class:"card-img-top" %>
                  <div class="card-body">
                    <h5 class="card-title"><%= field.name %></h5>
                    <p class="card-text">$ <%= field.price %></p>
                    <%= link_to "More details", field_path(field)%>
                    <% if current_user.admin_user == true %>
                      <p><%= link_to 'Delete', field_path(field), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}  %></p>
                    <% end %>
                  </div>
                </div>
              </div>
            <% end %>
            <div class="col-6 mt-3" style="width: 100%; height: 600px;"
              data-controller="map"
              data-map-markers-value="<%= @markers.to_json %>"
              data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
            </div>
        </div>
      </div>

</body>

app/views/fields/new.html.erb
<body style="background-color: #667F63">

<%if policy(@field).new? %>
  <%= link_to "Create a field", new_field_path(@field) %>
<% end %>
<%= button_to "Create field", @field, method: :delete if policy(@field).destroy? %>


<div class="container mt-5 text-white">
  <%= simple_form_for(@field) do |f| %>
   <%= f.input :photo, as: :file %>
    <%= f.input :name %>
    <%= f.input :price %>
    <%= f.input :address %>
    <%= f.input :number_of_players %>
    <%= f.submit%>
  <% end %>

  <div class = 'pt-3 mb-5'>
    <%= link_to "Back to Index", fields_path%>
  </div>
</div>
</body>

app/views/fields/show.html.erb
<%# <body style = "background-color: #667F63"> %>
  <div class="container d-flex p-5 justify-content-center">

    <div class="col">
      <div class="h-100 img-fluid">
       <%= cl_image_tag @field.photo.key, height: 550, width: 400 %>
      </div>
    </div>

    <div class = "col text-center">
      <h1 class = "text-uppercase pt-3"><%= @field.name%></h1>
      <p class= 'fs-4'><strong>$<%= @field.price %></strong></p>
      <p class= 'fs-4'><%= @field.address %></p>
      <p class= 'fs-4'><%= @field.number_of_players %> players</p>
      <div class="ms-5 me-5 p-5">
        <%= simple_form_for [@field, @booking], data: { controller: 'flatpickr' } do |f| %>
          <%= f.input :start_time, as: :string, input_html: { data: { flatpickr_target: "startTime" } } %>
          <%= f.input :end_time, as: :string, input_html: { data: { flatpickr_target: "endTime" }, id: 'end_time' } %>
          <%= f.submit 'Reserve your spot' %>
        <% end %>
        <br>
        <%= link_to "Back to Index", fields_path  %>
      </div>
    </div>

  </div>
<%# </body> %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BoraJogar</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body><%= render "shared/navbar" %>
<%= render "shared/flashes" %>
  <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
  <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class = "bg-img">
  <h1 class = "centered">Bora Jogar?</h1>
  <div class = "button">Find a field</div>
  </div>


<div class = "container p-4">
  <div class="">
    <%= image_tag 'soccer_ball.jpg', class: 'h-25 w-25 rounded', alt: "soccer ball"%>
  </div>
  <div class="">
    <%= image_tag 'soccer_player.jpg', class: 'h-25 w-25 rounded', alt: "soccer player"%>
  </div>
</div>

<footer class="absolute text-center text-white" style="background-color:#495057;">
  <div class="container pt-5">
    <section class="mb-5">

      <a
        class="btn btn-link btn-floating btn-lg text-white m-1"
        href="#!"
        role="button"
        data-mdb-ripple-color="white"
        ><i class="fab fa-facebook-f"></i
      ></a>

      <a
        class="btn btn-link btn-floating btn-lg text-white m-1"
        href="#!"
        role="button"
        data-mdb-ripple-color="white"
        ><i class="fab fa-twitter"></i
      ></a>

      <a
        class="btn btn-link btn-floating btn-lg text-white m-1"
        href="#!"
        role="button"
        data-mdb-ripple-color="white"
        ><i class="fab fa-instagram"></i
      ></a>

      <a
        class="btn btn-link btn-floating btn-lg text-white m-1"
        href="#!"
        role="button"
        data-mdb-ripple-color="white"
        ><i class="fab fa-linkedin"></i
      ></a>
    </section>
  </div>

  <div class="text-center text-white p-3" style="background-color: rgba(0, 0, 0, 0.2);">
  </div>
</footer>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon" style="background-color:#495057;">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "logo.png", style: 'width:120px;' %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link text-white" %>
          </li>
          <%# <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link text-white" %>
          <%# </li> %>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Profile", user_path(current_user), class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link text-white" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container d-flex p-5 justify-content-center">

    <%# <div class="col">
      <div class="h-100 img-fluid">
       <%= cl_image_tag @user.photo.key, height: 550, width: 400 %>
      <%# </div>
    </div> %>

    <div class = "col">
      <h1 class = "text-capitalize pt-3"><%= @user.name%></h1>
      <p class= 'fs-4'><strong>email: </strong><%= @user.email %></p>
      <p class= 'fs-4'><strong>phone number: </strong><%= @user.phone_number %></p>
      <p class= 'fs-4'><strong>address: </strong><%= @user.address %></p>
      <p class= 'fs-4'><strong>birthday: </strong><%= @user.birthday %></p>
    </div>

    <div>
      <% @user.bookings.each do |booking| %>
      <%= booking.field%>
      <% end %>
    </div>

  </div>